CREATE TABLE IF NOT EXISTS Genre(
	GenreID INTEGER PRIMARY KEY,
	GenreName VARCHAR(60) NOT NULL
);

CREATE TABLE IF NOT EXISTS Artist(
	ArtistID INTEGER PRIMARY KEY,
	ArtistName VARCHAR(60) UNIQUE NOT NULL
);

CREATE TABLE IF NOT EXISTS Album(
	AlbumID INTEGER PRIMARY KEY,
	AlbumName VARCHAR(60) NOT NULL,
	Year INTEGER NOT NULL CHECK (Year >= 1900 AND Year <= EXTRACT(YEAR FROM CURRENT_DATE))
	
);

CREATE TABLE IF NOT EXISTS Track(
	TrackID INTEGER PRIMARY KEY,
	TrackName VARCHAR(60) NOT NULL,
	Duration INTEGER NOT NULL CHECK (Duration > 0 AND Duration <= 600),
	AlbumID INTEGER REFERENCES Album(AlbumID)
	
);

CREATE TABLE IF NOT EXISTS Sbornik(
	SbornikID INTEGER PRIMARY KEY,
	SbornikName VARCHAR(60) NOT NULL,
	Year INTEGER NOT NULL CHECK (Year >= 1900 AND Year <= EXTRACT(YEAR FROM CURRENT_DATE))
);

CREATE TABLE IF NOT EXISTS Artist_Genre(
	GenreID INTEGER REFERENCES Genre(GenreID),
	ArtistID INTEGER REFERENCES Artist(ArtistID)
);

CREATE TABLE IF NOT EXISTS Album_Artist(
	AlbumID INTEGER REFERENCES Album(AlbumID),
	ArtistID INTEGER REFERENCES Artist(ArtistID)
);

CREATE TABLE IF NOT EXISTS Sbornik_Track(
	SbornikID INTEGER REFERENCES Sbornik(SbornikID),
	TrackID INTEGER REFERENCES Track(TrackID)
);